# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    container_name: balance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: balance
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U balance -d balance"]
      interval: 5s
      timeout: 3s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: balance-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.cl
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
